In [1]:
import sys
import numpy as np

In [2]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [3]:
a = np.array([1,2,3,4])
b = np.array([0 , 0.5 , 1 , 1.5 ])

In [6]:
a[0] , a[1] , a[2] , a[3] , b[1]

(1, 2, 3, 4, 0.5)

In [14]:
a[0:], b[0:]

(array([1, 2, 3, 4]), array([0. , 0.5, 1. , 1.5]))

In [17]:
a[1:3]

array([2, 3])

In [18]:
a[1:-1]

array([2, 3])

In [19]:
a[-1]

4

In [20]:
a[::2]

array([1, 3])

In [22]:
a , b

(array([1, 2, 3, 4]), array([0. , 0.5, 1. , 1.5]))

In [24]:
a.dtype , b.dtype

(dtype('int32'), dtype('float64'))

In [30]:
 c = np.array(['z','c','a','f'])

In [28]:
c.dtype

dtype('<U1')

In [37]:
A = np.array([
    [ 1,2,3],
    [ 4,5,6]
])

In [38]:
A.shape


(2, 3)

In [39]:
A.ndim

2

In [40]:
A.size

6

In [45]:
B = np.array([
    [
    
    [1,2,3],
    [4,8,9]
    ],
    
    [
    
    [4,8,50],
    [7,25,6]
    ],
    
    [
    [ 1,2,3],
    [ 4,5,6]
    ]
    
])

In [46]:
B

array([[[ 1,  2,  3],
        [ 4,  8,  9]],

       [[ 4,  8, 50],
        [ 7, 25,  6]],

       [[ 1,  2,  3],
        [ 4,  5,  6]]])

In [47]:
B.shape

(3, 2, 3)

In [48]:
B.size

18

In [49]:
B.ndim

3

In [50]:
B.dtype

dtype('int32')

In [51]:
A = np.array([
#.   0. 1. 2
    [1, 2, 3], # 0
    [4, 5, 6], # 1
    [7, 8, 9]  # 2
])

In [52]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [58]:
A[0][2]

3

In [54]:
A[0]

array([1, 2, 3])

In [55]:
A[2]

array([7, 8, 9])

In [61]:
A[:, :1]

array([[1],
       [4],
       [7]])

In [69]:
A[1] = np.array([10,15,4])

In [63]:
A

array([[ 1,  2,  3],
       [10, 15,  4],
       [ 7,  8,  9]])

In [64]:
A[2] = 98

In [65]:
A

array([[ 1,  2,  3],
       [10, 15,  4],
       [98, 98, 98]])

In [70]:
a = np.array([1, 2, 3, 4,4])

In [71]:
a

array([1, 2, 3, 4, 4])

In [72]:
a.sum()

14

In [73]:
a.mean()

2.8

In [77]:
a.std()

1.16619037896906

In [78]:
a.var()

1.3599999999999999

In [79]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])


In [80]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [84]:
A.sum()

45

In [83]:
A.std()

2.581988897471611

In [82]:
A.var()

6.666666666666667

In [81]:
A.mean()

5.0

In [85]:
A.sum(axis=0)

array([12, 15, 18])

In [86]:
A.sum(axis=1)

array([ 6, 15, 24])

In [87]:
A.mean(axis=0)

array([4., 5., 6.])

In [88]:
A.std(axis=0)

array([2.44948974, 2.44948974, 2.44948974])

In [89]:
A.var(axis=0)

array([6., 6., 6.])

In [90]:
A.mean(axis=1)

array([2., 5., 8.])

In [91]:
A.std(axis=1)

array([0.81649658, 0.81649658, 0.81649658])

In [92]:
A.var(axis=1)

array([0.66666667, 0.66666667, 0.66666667])

In [93]:
a

array([1, 2, 3, 4, 4])

In [102]:
a = np.arange(0,10)

In [103]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [106]:
b = a+10

In [105]:
a*10

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [107]:
b

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [108]:
b+10

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [109]:
b*10

array([100, 110, 120, 130, 140, 150, 160, 170, 180, 190])

In [111]:
c = np.arange(80,90)

In [112]:
c

array([80, 81, 82, 83, 84, 85, 86, 87, 88, 89])

In [113]:
a + b + c

array([ 90,  93,  96,  99, 102, 105, 108, 111, 114, 117])

In [115]:
a *b *c

array([    0,   891,  1968,  3237,  4704,  6375,  8256, 10353, 12672,
       15219])

In [116]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [117]:
a[0] , a[-1]

(0, 9)

In [118]:
a[[0, -1]]

array([0, 9])

In [120]:
a >= 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [121]:
a[a >= 2]

array([2, 3, 4, 5, 6, 7, 8, 9])

In [122]:
a.mean()

4.5

In [123]:
a[a > a.mean()]

array([5, 6, 7, 8, 9])

In [124]:
A = np.random.randint(100, size=(3, 3))

In [125]:
A

array([[43, 65, 75],
       [95, 89, 81],
       [54, 57, 70]])

In [133]:
B = np.random.randint(258, size=(6,6))

In [134]:
B

array([[156, 128, 164, 235, 119,  41],
       [ 54, 240,   3, 194,  78,  80],
       [ 74, 118,   7, 177, 108, 131],
       [ 41, 242, 199, 203,  51, 178],
       [212, 117, 148,  42, 214, 148],
       [152, 141, 249, 170, 207,   9]])

In [137]:
A > 50 , B > 150

(array([[False,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]]),
 array([[ True, False,  True,  True, False, False],
        [False,  True, False,  True, False, False],
        [False, False, False,  True, False, False],
        [False,  True,  True,  True, False,  True],
        [ True, False, False, False,  True, False],
        [ True, False,  True,  True,  True, False]]))

In [138]:
B[B>125]

array([156, 128, 164, 235, 240, 194, 177, 131, 242, 199, 203, 178, 212,
       148, 214, 148, 152, 141, 249, 170, 207])

In [140]:
A[A>65]

array([75, 95, 89, 81, 70])

In [148]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [142]:
B = np.array([
    [6, 5],
    [4, 3],
    [2, 1]
])

In [144]:
A.dot(B)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [146]:
A@B

array([[20, 14],
       [56, 41],
       [92, 68]])

In [147]:
B.T

array([[6, 4, 2],
       [5, 3, 1]])

In [149]:
A.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [154]:
import pandas as pd
import numpy as np

In [155]:
g7 = pd.Series([35.467, 63.951, 80.940, 60.665, 127.061, 64.511, 318.523])

In [156]:
g7

0     35.467
1     63.951
2     80.940
3     60.665
4    127.061
5     64.511
6    318.523
dtype: float64

In [157]:
g7.name = "G7 Countries population name "

In [158]:
g7

0     35.467
1     63.951
2     80.940
3     60.665
4    127.061
5     64.511
6    318.523
Name: G7 Countries population name , dtype: float64

In [160]:
g7.dtype

dtype('float64')

In [161]:
g7.values

array([ 35.467,  63.951,  80.94 ,  60.665, 127.061,  64.511, 318.523])

In [162]:
type(g7.values)

numpy.ndarray

In [163]:
g7

0     35.467
1     63.951
2     80.940
3     60.665
4    127.061
5     64.511
6    318.523
Name: G7 Countries population name , dtype: float64

In [164]:
g7[0]

35.467

In [165]:
g7[1]

63.951

In [166]:
g7[2]

80.94

In [168]:
g7.index

RangeIndex(start=0, stop=7, step=1)

In [172]:
g7.index = [
    'Canada',
    'France',
    'Germany',
    'Italy',
    'Japan',
    'United Kingdom',
    'United States'
]

In [173]:
g7

Canada             35.467
France             63.951
Germany            80.940
Italy              60.665
Japan             127.061
United Kingdom     64.511
United States     318.523
Name: G7 Countries population name , dtype: float64

In [179]:
pd.Series({
     'Canada'  :        35.467,
     'France'   :       63.951,
     'Germany'   :      80.940,
     'Italy'      :     60.665,
     'Japan'       :    127.061,
     'United Kingdom' : 64.511,
     'United States':   318.523,
    
},name='G7 Population in millions')

Canada             35.467
France             63.951
Germany            80.940
Italy              60.665
Japan             127.061
United Kingdom     64.511
United States     318.523
Name: G7 Population in millions, dtype: float64

In [180]:
pd.Series (
    [35.467, 63.951, 80.94, 60.665, 127.061, 64.511, 318.523],
    index = ['Canada', 'France', 'Germany', 'Italy', 'Japan', 'United Kingdom',
       'United States'], name='G7 Population in millions')

Canada             35.467
France             63.951
Germany            80.940
Italy              60.665
Japan             127.061
United Kingdom     64.511
United States     318.523
Name: G7 Population in millions, dtype: float64

In [182]:
pd.Series(g7 , index=['France', 'Germany', 'Italy', 'Spain'])

France     63.951
Germany    80.940
Italy      60.665
Spain         NaN
Name: G7 Countries population name , dtype: float64

In [183]:
g7

Canada             35.467
France             63.951
Germany            80.940
Italy              60.665
Japan             127.061
United Kingdom     64.511
United States     318.523
Name: G7 Countries population name , dtype: float64

In [185]:
g7['Canada']

35.467

In [186]:
g7['France']

63.951

In [193]:
g7['Canada ':'Italy ']

France     63.951
Germany    80.940
Italy      60.665
Name: G7 Countries population name , dtype: float64

In [195]:
g7>70

Canada            False
France            False
Germany            True
Italy             False
Japan              True
United Kingdom    False
United States      True
Name: G7 Countries population name , dtype: bool

In [196]:
g7[g7>70]

Germany           80.940
Japan            127.061
United States    318.523
Name: G7 Countries population name , dtype: float64

In [197]:
g7.mean()

107.30257142857144

In [198]:
g7.std()

97.24996987121581

In [199]:
g7.var()

9457.556639952383

In [200]:
g7* 1000000

Canada             35467000.0
France             63951000.0
Germany            80940000.0
Italy              60665000.0
Japan             127061000.0
United Kingdom     64511000.0
United States     318523000.0
Name: G7 Countries population name , dtype: float64

In [201]:
g7.mean()

107.30257142857144

In [202]:
g7['France': 'Italy'].mean()

68.51866666666666

In [204]:
g7[(g7>80) | (g7<40)] 

Canada            35.467
Germany           80.940
Japan            127.061
United States    318.523
Name: G7 Countries population name , dtype: float64

In [206]:
g7[(g7>80) & (g7<200)]

Germany     80.940
Japan      127.061
Name: G7 Countries population name , dtype: float64

In [207]:
g7['Canada'] = 40.5

In [208]:
g7

Canada             40.500
France             63.951
Germany            80.940
Italy              60.665
Japan             127.061
United Kingdom     64.511
United States     318.523
Name: G7 Countries population name , dtype: float64

In [209]:
g7.iloc[-1] = 500

In [210]:
g7

Canada             40.500
France             63.951
Germany            80.940
Italy              60.665
Japan             127.061
United Kingdom     64.511
United States     500.000
Name: G7 Countries population name , dtype: float64

In [211]:
g7[g7<70]

Canada            40.500
France            63.951
Italy             60.665
United Kingdom    64.511
Name: G7 Countries population name , dtype: float64

In [212]:
g7[g7<70] = 99.99

In [213]:
g7

Canada             99.990
France             99.990
Germany            80.940
Italy              99.990
Japan             127.061
United Kingdom     99.990
United States     500.000
Name: G7 Countries population name , dtype: float64

In [216]:
df = pd.DataFrame({
    'Population': [35.467, 63.951, 80.94 , 60.665, 127.061, 64.511, 318.523],
    'GDP': [1785387,2833687,3874437,2167744,4602367,2950039,17348075],
    'Surface Area': [9984670, 640679, 357114,301336,377930,242495,9525067],
    'HDI': [0.913,  0.888,  0.916, 0.873, 0.891, 0.907,0.915 ],
    'Continent': [ 'America', 'Europe','Europe','Europe','Asia', 'Europe', 'America']}, 
    columns=['Population', 'GDP', 'Surface Area', 'HDI', 'Continent'])

In [217]:
df

Population       GDP  Surface Area    HDI Continent
0      35.467   1785387       9984670  0.913   America
1      63.951   2833687        640679  0.888    Europe
2      80.940   3874437        357114  0.916    Europe
3      60.665   2167744        301336  0.873    Europe
4     127.061   4602367        377930  0.891      Asia
5      64.511   2950039        242495  0.907    Europe
6     318.523  17348075       9525067  0.915   America

In [218]:
df.index = [
     'Canada',
    'France',
    'Germany',
    'Italy',
    'Japan',
    'United Kingdom',
    'United States',
]

In [219]:
df

Population       GDP  Surface Area    HDI Continent
Canada              35.467   1785387       9984670  0.913   America
France              63.951   2833687        640679  0.888    Europe
Germany             80.940   3874437        357114  0.916    Europe
Italy               60.665   2167744        301336  0.873    Europe
Japan              127.061   4602367        377930  0.891      Asia
United Kingdom      64.511   2950039        242495  0.907    Europe
United States      318.523  17348075       9525067  0.915   America

In [220]:
df.columns

Index(['Population', 'GDP', 'Surface Area', 'HDI', 'Continent'], dtype='object')

In [221]:
df.index

Index(['Canada', 'France', 'Germany', 'Italy', 'Japan', 'United Kingdom',
       'United States'],
      dtype='object')

In [222]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7 entries, Canada to United States
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   Population    7 non-null      float64
 1   GDP           7 non-null      int64  
 2   Surface Area  7 non-null      int64  
 3   HDI           7 non-null      float64
 4   Continent     7 non-null      object 
dtypes: float64(2), int64(2), object(1)
memory usage: 336.0+ bytes


In [223]:
df.size

35

In [228]:
df.shape

(7, 5)

In [226]:
df.describe()

Population           GDP  Surface Area       HDI
count    7.000000  7.000000e+00  7.000000e+00  7.000000
mean   107.302571  5.080248e+06  3.061327e+06  0.900429
std     97.249970  5.494020e+06  4.576187e+06  0.016592
min     35.467000  1.785387e+06  2.424950e+05  0.873000
25%     62.308000  2.500716e+06  3.292250e+05  0.889500
50%     64.511000  2.950039e+06  3.779300e+05  0.907000
75%    104.000500  4.238402e+06  5.082873e+06  0.914000
max    318.523000  1.734808e+07  9.984670e+06  0.916000

In [229]:
df.dtypes

Population      float64
GDP               int64
Surface Area      int64
HDI             float64
Continent        object
dtype: object

In [230]:
df.dtypes.value_counts()

float64    2
int64      2
object     1
dtype: int64

In [ ]:
#Indexing, Selection and Slicing¶

In [231]:
df

Population       GDP  Surface Area    HDI Continent
Canada              35.467   1785387       9984670  0.913   America
France              63.951   2833687        640679  0.888    Europe
Germany             80.940   3874437        357114  0.916    Europe
Italy               60.665   2167744        301336  0.873    Europe
Japan              127.061   4602367        377930  0.891      Asia
United Kingdom      64.511   2950039        242495  0.907    Europe
United States      318.523  17348075       9525067  0.915   America

In [233]:
df.loc['Canada']

Population       35.467
GDP             1785387
Surface Area    9984670
HDI               0.913
Continent       America
Name: Canada, dtype: object

In [235]:
df.iloc[0] , df.iloc[-1]

(Population       35.467
 GDP             1785387
 Surface Area    9984670
 HDI               0.913
 Continent       America
 Name: Canada, dtype: object,
 Population       318.523
 GDP             17348075
 Surface Area     9525067
 HDI                0.915
 Continent        America
 Name: United States, dtype: object)

In [237]:
df['Population']

Canada             35.467
France             63.951
Germany            80.940
Italy              60.665
Japan             127.061
United Kingdom     64.511
United States     318.523
Name: Population, dtype: float64

In [238]:
df['Population'].to_frame()

Population
Canada              35.467
France              63.951
Germany             80.940
Italy               60.665
Japan              127.061
United Kingdom      64.511
United States      318.523

In [239]:
df[['Population', 'GDP']]

Population       GDP
Canada              35.467   1785387
France              63.951   2833687
Germany             80.940   3874437
Italy               60.665   2167744
Japan              127.061   4602367
United Kingdom      64.511   2950039
United States      318.523  17348075

In [240]:
df[1:3]

Population      GDP  Surface Area    HDI Continent
France       63.951  2833687        640679  0.888    Europe
Germany      80.940  3874437        357114  0.916    Europe

In [241]:
df.loc['Italy']

Population       60.665
GDP             2167744
Surface Area     301336
HDI               0.873
Continent        Europe
Name: Italy, dtype: object

In [243]:
df.loc['France':'Italy']

Population      GDP  Surface Area    HDI Continent
France       63.951  2833687        640679  0.888    Europe
Germany      80.940  3874437        357114  0.916    Europe
Italy        60.665  2167744        301336  0.873    Europe

In [244]:
df.loc['France':'Italy','Population']

France     63.951
Germany    80.940
Italy      60.665
Name: Population, dtype: float64

In [246]:
df.loc['France':'Italy',['Population','GDP']]

Population      GDP
France       63.951  2833687
Germany      80.940  3874437
Italy        60.665  2167744

In [247]:
df

Population       GDP  Surface Area    HDI Continent
Canada              35.467   1785387       9984670  0.913   America
France              63.951   2833687        640679  0.888    Europe
Germany             80.940   3874437        357114  0.916    Europe
Italy               60.665   2167744        301336  0.873    Europe
Japan              127.061   4602367        377930  0.891      Asia
United Kingdom      64.511   2950039        242495  0.907    Europe
United States      318.523  17348075       9525067  0.915   America

In [248]:
df.iloc[[0, 1, -1]]

Population       GDP  Surface Area    HDI Continent
Canada             35.467   1785387       9984670  0.913   America
France             63.951   2833687        640679  0.888    Europe
United States     318.523  17348075       9525067  0.915   America

In [249]:
df['Population']>70

Canada            False
France            False
Germany            True
Italy             False
Japan              True
United Kingdom    False
United States      True
Name: Population, dtype: bool

In [252]:
df.loc[df['Population']>73] 

Population       GDP  Surface Area    HDI Continent
Germany            80.940   3874437        357114  0.916    Europe
Japan             127.061   4602367        377930  0.891      Asia
United States     318.523  17348075       9525067  0.915   America

In [256]:
df.loc[df['Population']>73 , 'Population']

Germany           80.940
Japan            127.061
United States    318.523
Name: Population, dtype: float64

In [255]:
df.loc[df['Population']>73 , ['Population','GDP']]

Population       GDP
Germany            80.940   3874437
Japan             127.061   4602367
United States     318.523  17348075

In [ ]:
#DROPPING STUFF

In [257]:
df.drop('Canada')

Population       GDP  Surface Area    HDI Continent
France              63.951   2833687        640679  0.888    Europe
Germany             80.940   3874437        357114  0.916    Europe
Italy               60.665   2167744        301336  0.873    Europe
Japan              127.061   4602367        377930  0.891      Asia
United Kingdom      64.511   2950039        242495  0.907    Europe
United States      318.523  17348075       9525067  0.915   America

In [259]:
df.drop(['Canada','Japan'])

Population       GDP  Surface Area    HDI Continent
France              63.951   2833687        640679  0.888    Europe
Germany             80.940   3874437        357114  0.916    Europe
Italy               60.665   2167744        301336  0.873    Europe
United Kingdom      64.511   2950039        242495  0.907    Europe
United States      318.523  17348075       9525067  0.915   America

In [260]:
df.drop(columns=['Population','GDP'])

Surface Area    HDI Continent
Canada               9984670  0.913   America
France                640679  0.888    Europe
Germany               357114  0.916    Europe
Italy                 301336  0.873    Europe
Japan                 377930  0.891      Asia
United Kingdom        242495  0.907    Europe
United States        9525067  0.915   America

In [263]:
df.drop(['Italy','Canada'],axis=0)

Population       GDP  Surface Area    HDI Continent
France              63.951   2833687        640679  0.888    Europe
Germany             80.940   3874437        357114  0.916    Europe
Japan              127.061   4602367        377930  0.891      Asia
United Kingdom      64.511   2950039        242495  0.907    Europe
United States      318.523  17348075       9525067  0.915   America

In [265]:
df.drop(['Italy','Canada'],axis='rows')

Population       GDP  Surface Area    HDI Continent
France              63.951   2833687        640679  0.888    Europe
Germany             80.940   3874437        357114  0.916    Europe
Japan              127.061   4602367        377930  0.891      Asia
United Kingdom      64.511   2950039        242495  0.907    Europe
United States      318.523  17348075       9525067  0.915   America

In [264]:
df.drop(columns=['Population','GDP'], axis = 1)

Surface Area    HDI Continent
Canada               9984670  0.913   America
France                640679  0.888    Europe
Germany               357114  0.916    Europe
Italy                 301336  0.873    Europe
Japan                 377930  0.891      Asia
United Kingdom        242495  0.907    Europe
United States        9525067  0.915   America

In [266]:
df.drop(columns=['Population','GDP'], axis = 'columns')

Surface Area    HDI Continent
Canada               9984670  0.913   America
France                640679  0.888    Europe
Germany               357114  0.916    Europe
Italy                 301336  0.873    Europe
Japan                 377930  0.891      Asia
United Kingdom        242495  0.907    Europe
United States        9525067  0.915   America

In [ ]:
#operations

In [267]:
df[['Population','GDP']]

Population       GDP
Canada              35.467   1785387
France              63.951   2833687
Germany             80.940   3874437
Italy               60.665   2167744
Japan              127.061   4602367
United Kingdom      64.511   2950039
United States      318.523  17348075

In [268]:
df[['Population','GDP']]/100

Population        GDP
Canada             0.35467   17853.87
France             0.63951   28336.87
Germany            0.80940   38744.37
Italy              0.60665   21677.44
Japan              1.27061   46023.67
United Kingdom     0.64511   29500.39
United States      3.18523  173480.75

In [270]:
crisis = pd.Series([-1000000,-0.3],index=['GDP','HDI'])

In [271]:
crisis

GDP   -1000000.0
HDI         -0.3
dtype: float64

In [273]:
df[['GDP','HDI']] + crisis

GDP    HDI
Canada            785387.0  0.613
France           1833687.0  0.588
Germany          2874437.0  0.616
Italy            1167744.0  0.573
Japan            3602367.0  0.591
United Kingdom   1950039.0  0.607
United States   16348075.0  0.615

In [ ]:
#Modifing data frames

In [275]:
lang = pd.Series(
    ["French","German","Italy","Japanies"],
    index = ["France","Germany","Italy","Japan"], 
    name = "Language"


)

In [276]:
lang

France       French
Germany      German
Italy         Italy
Japan      Japanies
Name: Language, dtype: object

In [278]:
df['Language'] = lang

In [279]:
df

Population       GDP  Surface Area    HDI Continent  Language
Canada              35.467   1785387       9984670  0.913   America       NaN
France              63.951   2833687        640679  0.888    Europe    French
Germany             80.940   3874437        357114  0.916    Europe    German
Italy               60.665   2167744        301336  0.873    Europe     Italy
Japan              127.061   4602367        377930  0.891      Asia  Japanies
United Kingdom      64.511   2950039        242495  0.907    Europe       NaN
United States      318.523  17348075       9525067  0.915   America       NaN

In [280]:
df['Language'] = 'English'   #Replacing values per column

In [282]:
df  #Replacing values per column

Population       GDP  Surface Area    HDI Continent Language
Canada              35.467   1785387       9984670  0.913   America  English
France              63.951   2833687        640679  0.888    Europe  English
Germany             80.940   3874437        357114  0.916    Europe  English
Italy               60.665   2167744        301336  0.873    Europe  English
Japan              127.061   4602367        377930  0.891      Asia  English
United Kingdom      64.511   2950039        242495  0.907    Europe  English
United States      318.523  17348075       9525067  0.915   America  English

In [ ]:
#Renaming Columns

In [283]:
df.rename(
    columns =  {
        'HDI' :'human development index',
        'GDP' : 'gross domestic product',
        'Anual Popcorn Consumption': 'APC'
    } ,index = 
    {
        'United Kingdom':'UK',
        'United States' : 'USA',
        'Argentina': 'MESSI'
    })

Population  gross domestic product  Surface Area  \
Canada       35.467                 1785387       9984670   
France       63.951                 2833687        640679   
Germany      80.940                 3874437        357114   
Italy        60.665                 2167744        301336   
Japan       127.061                 4602367        377930   
UK           64.511                 2950039        242495   
USA         318.523                17348075       9525067   

         human development index Continent Language  
Canada                     0.913   America  English  
France                     0.888    Europe  English  
Germany                    0.916    Europe  English  
Italy                      0.873    Europe  English  
Japan                      0.891      Asia  English  
UK                         0.907    Europe  English  
USA                        0.915   America  English

In [284]:
df.rename(index=str.upper)

Population       GDP  Surface Area    HDI Continent Language
CANADA              35.467   1785387       9984670  0.913   America  English
FRANCE              63.951   2833687        640679  0.888    Europe  English
GERMANY             80.940   3874437        357114  0.916    Europe  English
ITALY               60.665   2167744        301336  0.873    Europe  English
JAPAN              127.061   4602367        377930  0.891      Asia  English
UNITED KINGDOM      64.511   2950039        242495  0.907    Europe  English
UNITED STATES      318.523  17348075       9525067  0.915   America  English

In [286]:
df.rename(index=lambda x: x.lower())

Population       GDP  Surface Area    HDI Continent Language
canada              35.467   1785387       9984670  0.913   America  English
france              63.951   2833687        640679  0.888    Europe  English
germany             80.940   3874437        357114  0.916    Europe  English
italy               60.665   2167744        301336  0.873    Europe  English
japan              127.061   4602367        377930  0.891      Asia  English
united kingdom      64.511   2950039        242495  0.907    Europe  English
united states      318.523  17348075       9525067  0.915   America  English

In [ ]:
#dropping columns

In [287]:
df.drop(columns='Language', inplace=True)

In [288]:
df

Population       GDP  Surface Area    HDI Continent
Canada              35.467   1785387       9984670  0.913   America
France              63.951   2833687        640679  0.888    Europe
Germany             80.940   3874437        357114  0.916    Europe
Italy               60.665   2167744        301336  0.873    Europe
Japan              127.061   4602367        377930  0.891      Asia
United Kingdom      64.511   2950039        242495  0.907    Europe
United States      318.523  17348075       9525067  0.915   America

In [ ]:
#adding values

In [292]:
x = df.append(pd.Series({
    'Population': 1426,
    'GDP':5},
    name = "china"
))

In [293]:
x

Population         GDP  Surface Area    HDI Continent
Canada              35.467   1785387.0     9984670.0  0.913   America
France              63.951   2833687.0      640679.0  0.888    Europe
Germany             80.940   3874437.0      357114.0  0.916    Europe
Italy               60.665   2167744.0      301336.0  0.873    Europe
Japan              127.061   4602367.0      377930.0  0.891      Asia
United Kingdom      64.511   2950039.0      242495.0  0.907    Europe
United States      318.523  17348075.0     9525067.0  0.915   America
china             1426.000         5.0           NaN    NaN       NaN

In [294]:
df

Population       GDP  Surface Area    HDI Continent
Canada              35.467   1785387       9984670  0.913   America
France              63.951   2833687        640679  0.888    Europe
Germany             80.940   3874437        357114  0.916    Europe
Italy               60.665   2167744        301336  0.873    Europe
Japan              127.061   4602367        377930  0.891      Asia
United Kingdom      64.511   2950039        242495  0.907    Europe
United States      318.523  17348075       9525067  0.915   America

In [297]:
x.loc['china'] = pd.Series({'Continent':'Asia','Surface Area':17048075})

In [298]:
x

Population         GDP  Surface Area    HDI Continent
Canada              35.467   1785387.0     9984670.0  0.913   America
France              63.951   2833687.0      640679.0  0.888    Europe
Germany             80.940   3874437.0      357114.0  0.916    Europe
Italy               60.665   2167744.0      301336.0  0.873    Europe
Japan              127.061   4602367.0      377930.0  0.891      Asia
United Kingdom      64.511   2950039.0      242495.0  0.907    Europe
United States      318.523  17348075.0     9525067.0  0.915   America
china                  NaN         NaN    17048075.0    NaN      Asia

In [299]:
df

Population         GDP  Surface Area    HDI Continent
Canada              35.467   1785387.0       9984670  0.913   America
France              63.951   2833687.0        640679  0.888    Europe
Germany             80.940   3874437.0        357114  0.916    Europe
Italy               60.665   2167744.0        301336  0.873    Europe
Japan              127.061   4602367.0        377930  0.891      Asia
United Kingdom      64.511   2950039.0        242495  0.907    Europe
United States      318.523  17348075.0       9525067  0.915   America
china                  NaN         NaN      17048075    NaN      Asia

In [300]:
df['GDP Per Capita'] = df['GDP'] / df['Population']

In [301]:
df

Population         GDP  Surface Area    HDI Continent  \
Canada              35.467   1785387.0       9984670  0.913   America   
France              63.951   2833687.0        640679  0.888    Europe   
Germany             80.940   3874437.0        357114  0.916    Europe   
Italy               60.665   2167744.0        301336  0.873    Europe   
Japan              127.061   4602367.0        377930  0.891      Asia   
United Kingdom      64.511   2950039.0        242495  0.907    Europe   
United States      318.523  17348075.0       9525067  0.915   America   
china                  NaN         NaN      17048075    NaN      Asia   

                GDP Per Capita  
Canada            50339.385908  
France            44310.284437  
Germany           47868.013343  
Italy             35733.025633  
Japan             36221.712406  
United Kingdom    45729.239975  
United States     54464.120330  
china                      NaN

In [302]:
df.head()

Population        GDP  Surface Area    HDI Continent  GDP Per Capita
Canada       35.467  1785387.0       9984670  0.913   America    50339.385908
France       63.951  2833687.0        640679  0.888    Europe    44310.284437
Germany      80.940  3874437.0        357114  0.916    Europe    47868.013343
Italy        60.665  2167744.0        301336  0.873    Europe    35733.025633
Japan       127.061  4602367.0        377930  0.891      Asia    36221.712406

In [303]:
df.describe()

Population           GDP  Surface Area       HDI  GDP Per Capita
count    7.000000  7.000000e+00  8.000000e+00  7.000000        7.000000
mean   107.302571  5.080248e+06  4.809671e+06  0.900429    44952.254576
std     97.249970  5.494020e+06  6.511796e+06  0.016592     6954.983875
min     35.467000  1.785387e+06  2.424950e+05  0.873000    35733.025633
25%     62.308000  2.500716e+06  3.431695e+05  0.889500    40265.998421
50%     64.511000  2.950039e+06  5.093045e+05  0.907000    45729.239975
75%    104.000500  4.238402e+06  9.639968e+06  0.914000    49103.699626
max    318.523000  1.734808e+07  1.704808e+07  0.916000    54464.120330

In [304]:
population = df['Population']

In [305]:
population.min() , population.max()

(35.467, 318.523)

In [306]:
population.sum()

751.118

In [307]:
population.sum()/len(population)

93.88975

In [308]:
population.mean()

107.30257142857144

In [309]:
population.median()

64.511

In [310]:
population.std()

97.24996987121581

In [311]:
population.describe()

count      7.000000
mean     107.302571
std       97.249970
min       35.467000
25%       62.308000
50%       64.511000
75%      104.000500
max      318.523000
Name: Population, dtype: float64