In [2]:
import numpy as np


In [2]:
x = numpy.array([1,2,2,3,4,5])
print(x)

[1 2 2 3 4 5]


In [5]:
print(np.__version__)

1.18.1


In [6]:
np.array(42)

array(42)

In [9]:
a = np.array([[[1,2,3],[3,2,1]],[[4,5,6],[6,5,4]]])
print(a)

[[[1 2 3]
  [3 2 1]]

 [[4 5 6]
  [6 5 4]]]


In [12]:
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [18]:
p = np.array(42)
q = np.array([1,2,2,3,4,5])
b = np.array([[1,2,3],[4,5,6]])
a = np.array([ [[1,2,3],[3,2,1]],[[4,5,6],[6,5,4]],[[1,2,3,4,5],[7,8,9,1,4,7]] ])

print(p.ndim)
print(q.ndim)
print(b.ndim)
print(a.ndim)
print(a)



0
1
2
3
[[[list([1, 2, 3]) list([3, 2, 1])]
  [list([4, 5, 6]) list([6, 5, 4])]
  [list([1, 2, 3, 4, 5]) list([7, 8, 9, 1, 4, 7])]]]


In [24]:
x = np.array([1,2,2,3,45,5])
print(x[0])
print(x[1])
print(x[2])
print(x[3])
print(x[-1])


1
2
2
3
5


In [25]:
print(x[0] + x[1])


3


In [31]:
b = np.array([[1,2,3,4,5,6,7],[4,5,6,5,4,7,85]])
print('2nd element on 2nd dim ',b[1,1])
print('5nd element on 2nd dim ',b[1,5])

2nd element on 2nd dim  5
5nd element on 2nd dim  7


In [37]:
a = np.array([[[1,2,3],[3,2,1]],[[4,5,6],[6,5,4]]])
print(a[1,1,0])
print(a[0,0,1])
print(a[0,1,0])
print(a[0,1,0])
print(a[1,1,2])
print(a[1,1,1])


6
2
3
3
4
5


In [38]:
b = np.array([[1,2,3,4,5,6,7],[4,5,6,5,4,7,85]])
print('last element on 2nd dim ',b[1,-1])
print('3nd element on 2nd dim ',b[1,-5])        ## negetive indexing

last element on 2nd dim  85
3nd element on 2nd dim  6


In [3]:
x = np.array([1,2,2,3,45,5])
x[1:5]
####x[start:end]

array([ 2,  2,  3, 45])

In [6]:
print(x[:1])
print(x[:2])
print(x[:3])
print(x[:4])

[1]
[1 2]
[1 2 2]
[1 2 2 3]


In [8]:
print(x[1:])
print(x[2:])
print(x[3:])
print(x[4:])

[ 2  2  3 45  5]
[ 2  3 45  5]
[ 3 45  5]
[45  5]


In [11]:
print
(x[-1:-3])

array([], dtype=int32)