In [1]:
# this option displays all calculations from a cell and not just the last one which is how it is set by default
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

# using packages - numpy
numpy, pandas, matplotlib, scikit-learn, nltk, over 130,000 packages are available (and growing)

In [82]:
# Functions and Methods are powerful but not all users need all of them all the time
# Packages are collection of Modules. Modules are individual .py files which specify functions, methods, types
# This helps only include the needed Packages 

In [4]:
# exploring numpy, for Math functionality

# three ways of invoking array method
from numpy import array 
array([1,2,3])

import numpy
numpy.array([1,2,3])

import numpy as np
np.array([1,2,3])

# the np.array style is widely followed

array([1, 2, 3])

array([1, 2, 3])

array([1, 2, 3])

In [5]:
# lists are flexible for storing sequences but math operations are not supported. numpy is ideal for those.
x =[100,200,300] # this is a list
type(x)

list

In [6]:
x_array = np.array(x)
type(x)
type(x_array)

list

numpy.ndarray

In [9]:
y = [5,10,20]
y_array**2

array([ 25, 100, 400], dtype=int32)

In [10]:
y_array = np.array(y)
x_array/y_array

array([20., 20., 15.])

In [18]:
x_array = np.array([10,20,30,40])
y_array = np.array([2,2,2,2])
x_array/y_array

array([ 5., 10., 15., 20.])

In [85]:
# numpy array can hold only values of same type, if different then they are all coerced to be same type
np.array([1,2,3,"True",False])

np.array([1,2,3,False])
# In the above, if we had a True it will be converted to 1
np.array([1,2,3,True])


array(['1', '2', '3', 'True', 'False'], dtype='<U11')

array([1, 2, 3, 0])

array([1, 2, 3, 1])

In [21]:
# subsetting numpy array
arr = np.array([1,2,3,4,5,6,7,8,9,10])
type(arr)
subst = arr < 6
arr[subst]

numpy.ndarray

array([1, 2, 3, 4, 5])

In [87]:
# 2 dimensional array

xarr2d = np.array([[1,2,3,4],[5,6,7,8]])
xarr2d
xarr2d.shape

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

(2, 4)

In [88]:
# accesing elements of a 2d array
xarr2d[0]
# two ways of accessing an element in the 1-D array 
xarr2d[0][2]
xarr2d[0,2]

array([1, 2, 3, 4])

3

3

In [89]:
# start with row 0 and until 1 (excl) i.e. just the first row, columns are not specified so fetch all
xarr2d[0:1,:]

array([[1, 2, 3, 4]])

In [90]:
# start with column 1 and go on until column 3 (excl), remember index starts with 0. Rows are not specified so all are fetched.
xarr2d[:, 1:3]

array([[2, 3],
       [6, 7]])

In [91]:
# start with row index 0 and go until 1 (excl) so just first row. 
# Within that fetch column index 2 onwards until 3 (excl) index so just the third column
xarr2d[0:1, 2:3]

array([[3]])

In [92]:
# combine multiple arrays and create a multidimensional array
xarr = np.array([1,2,3])
yarr = np.array([10,11,12,"13"])
zarr = np.array([True, False])
xarr
yarr
narr = np.array((xarr,yarr, zarr))
type(narr)
# access the index 1 of narr and the fetch element index 0 within that 
narr[1][0]

array([1, 2, 3])

array(['10', '11', '12', '13'], dtype='<U11')

numpy.ndarray

'10'

In [25]:
# stack indivdual arrays as columns, this requires them to be of same dimensions (try adding a fourth element to yarr)
xarr = np.array([1,2,3])
yarr = np.array([10,11,12])
np.column_stack((xarr,yarr)).shape
np.row_stack((xarr,yarr)).shape

(3, 2)

(2, 3)

In [26]:
# np.random.normal(mean, stdev, sample size)
# this returns a sample of specifie size randomly drawn from a normal distribution with given mean and stdev
# set the seed to a specific value so every run generates the same random numbers
np.random.seed(0)

In [29]:
height = np.round(np.random.normal(5, 10, 5), 0)
height
np.mean(height)

np.var(height)

np.std(height)

array([-21.,  12.,  14.,  -2.,  28.])

6.2

275.36

16.59397481015323

In [31]:
# Creating and handling matrices
# Rows are delimited by a semicolon, values by a space. 
# Call the mat function with the following string to create a matrix:

mtrx = np.mat('1 2 3; 4 5 6; 7 8 9')
print (mtrx)
type(mtrx)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


numpy.matrix

In [97]:
# invoke transpose method for the matrix
print(mtrx.T)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [98]:
# invert the matrix using I method
print(mtrx.I)

[[ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]
 [-6.30503948e+15  1.26100790e+16 -6.30503948e+15]
 [ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]]


In [100]:
mtrx.shape

(3, 3)

In [105]:
# create matrix from array
np.mat(np.arange(10).reshape(2, 5))

matrix([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [109]:
# create matrix from array
np.mat(np.array([1,2,3,4,5,6]).reshape(3,2))

matrix([[1, 2],
        [3, 4],
        [5, 6]])

In [33]:
# 1
arr = np.array([1, 2, 3, 4])
mat = np.mat(arr.reshape(2, 2))

# 2
arr = np.array([[1, 2], [3, 4]])
mat = np.mat(arr)

# 3
mtrx = np.mat('1 2 3; 4 5 6; 7 8 9')
mtrx[2][1]

8